In [16]:
import numpy as np

In [17]:
def sigmoid(x):
  return x*(1-x)

In [18]:
def sigmoid_derivative(x):
  return x*(1-x)

In [19]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0], [1], [1], [0]])
X, y

(array([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]),
 array([[0],
        [1],
        [1],
        [0]]))

In [20]:
np.random.seed(42)

In [21]:
input_size =2
hidden_size =3
output_size=1

In [22]:
w1 = np.random.uniform(size=(input_size,hidden_size))
b1 = np.zeros((1,hidden_size))
b1

array([[0., 0., 0.]])

In [23]:
w2 = np.random.uniform(size=(hidden_size,output_size))
b2 = np.zeros((1,output_size))
w2

array([[0.05808361],
       [0.86617615],
       [0.60111501]])

In [24]:
learning_rate =0.1

In [25]:
import numpy as np
for epoch in range(100):
  Z1 = np.dot(X,w1)+b1
  A1 = sigmoid(Z1)

  Z2 = np.dot(A1,w2)+b2
  A2 = sigmoid(Z2)

  error = y-A2
  loss = np.mean(np.square(error))

  d_A2 = error * sigmoid(A2)

  error_hidden = d_A2.dot(w2.T)
  d_A1 = error_hidden * sigmoid(A1)

  w2 += A1.T.dot(d_A2)*learning_rate
  b2 += np.sum(d_A2,axis=0,keepdims =True)*learning_rate
  w1 += X.T.dot(d_A1)*learning_rate
  b1 += np.sum(d_A1, axis=0,keepdims=True)*learning_rate

  if epoch%10==0:
    print(f"Epoch {epoch},Loss: {loss:.4f}")

Epoch 0,Loss: 0.3589
Epoch 10,Loss: 0.2978
Epoch 20,Loss: 0.3410
Epoch 30,Loss: 0.4178
Epoch 40,Loss: 0.4559
Epoch 50,Loss: 0.4626
Epoch 60,Loss: 0.4630
Epoch 70,Loss: 0.4628
Epoch 80,Loss: 0.4628
Epoch 90,Loss: 0.4629


In [26]:
print("\nFinal Predictio: ")
print(A2)


Final Predictio: 
[[ 0.17816881]
 [-0.0605796 ]
 [ 0.18502484]
 [ 0.17793809]]
